team:
  leader: "wang"
  phone: "13303995621"
  age: 5
  createDate: "2025-09-10"

spring:
  servlet:
    multipart:
      max-file-size: 10MB     # 单个上传文件大小限定为10M，默认值为1M
      max-request-size: 100MB # 单次上传文件大小限定为100M，默认值为10M