server:
  port: 8081

#spring:
#    application:
#        name: quickstart

  ##自定义配置，心情语录
  my:
    mood:
      today: 周五
      content: 期待周末
      author: "码农"

  ## 功能开关
  feature:
    helloSwitch: true
    closeMsg: "该接口正在维护，请10分钟后再来！！"